token_num: 37
tokens: [ 'e~',
          '9',
          'i',
          'O',
          'g',
          'e',
          'R',
          'N',
          'w',
          'n',
          'j',
          'A',
          'u',
          'k',
          'J',
          'v',
          'E',
          't',
          'f',
          'o~',
          '9~',
          'z',
          'b',
          '2',
          'a~',
          'a',
          's',
          'S',
          'y',
          'o',
          'd',
          'Z',
          'H',
          'l',
          'p',
          '@',
          'm' ]